/** S&P 500 and gold UCITS/ETP instruments for UK / II investors (1x, 2x, 3x). */
window.INSTRUMENTS_DATA = [
  {
    leverage: "1x",
    ticker: "SPYL",
    name: "State Street SPDR S&P 500 UCITS ETF Acc",
    ter: "0.03%",
    accDist: "Acc",
    currency: "USD",
    isin: "IE000XZSV718",
    issuer: "State Street / SPDR",
    notes: "Lowest-cost 1x acc; LSE USD listing; ISA/SIPP eligible",
  },
  {
    leverage: "1x",
    ticker: "SP5L",
    name: "Amundi Core S&P 500 Swap UCITS ETF Acc",
    ter: "0.05%",
    accDist: "Acc",
    currency: "GBP",
    isin: "LU1135865084",
    issuer: "Amundi",
    notes: "Synthetic swap; popular GBP LSE line",
  },
  {
    leverage: "1x",
    ticker: "SPXP",
    name: "Invesco S&P 500 UCITS ETF Acc",
    ter: "0.05%",
    accDist: "Acc",
    currency: "GBP",
    isin: "IE00B3YCGJ38",
    issuer: "Invesco",
    notes: "Synthetic swap; GBP share class on LSE",
  },
  {
    leverage: "1x",
    ticker: "CSP1",
    name: "iShares Core S&P 500 UCITS ETF Acc",
    ter: "0.07%",
    accDist: "Acc",
    currency: "GBP",
    isin: "IE00B5BMR087",
    issuer: "BlackRock iShares",
    notes: "Physical full replication; very large AUM",
  },
  {
    leverage: "1x",
    ticker: "VUAG",
    name: "Vanguard S&P 500 UCITS ETF Acc",
    ter: "0.07%",
    accDist: "Acc",
    currency: "GBP",
    isin: "IE00BFMXXD54",
    issuer: "Vanguard",
    notes: "Physical replication; GBP LSE listing",
  },
  {
    leverage: "1x",
    ticker: "SPY5",
    name: "State Street SPDR S&P 500 UCITS ETF Dist",
    ter: "0.03%",
    accDist: "Dist",
    currency: "USD / GBP",
    isin: "IE00B6YX5C33",
    issuer: "State Street / SPDR",
    notes: "Cheapest 1x dist; quarterly dividends",
  },
  {
    leverage: "1x",
    ticker: "VUSA",
    name: "Vanguard S&P 500 UCITS ETF Dist",
    ter: "0.07%",
    accDist: "Dist",
    currency: "USD",
    isin: "IE00B3XXRP09",
    issuer: "Vanguard",
    notes: "Physical; quarterly dist; also listed GBP (VUKE)",
  },
  {
    leverage: "1x",
    ticker: "IDUS",
    name: "iShares S&P 500 UCITS ETF USD Dist",
    ter: "0.07%",
    accDist: "Dist",
    currency: "USD",
    isin: "IE0031442068",
    issuer: "BlackRock iShares",
    notes: "Physical sample; quarterly dividends",
  },
  {
    leverage: "1x",
    ticker: "IUSA",
    name: "iShares Core S&P 500 UCITS ETF USD Dist",
    ter: "0.07%",
    accDist: "Dist",
    currency: "USD",
    isin: "IE00B4L5Y983",
    issuer: "BlackRock iShares",
    notes: "Core physical dist line; sibling to CSP1 acc",
  },
  {
    leverage: "2x",
    ticker: "XS2D / DBPG",
    name: "Xtrackers S&P 500 2x Leveraged Daily Swap UCITS ETF 1C",
    ter: "0.60%",
    accDist: "Acc",
    currency: "EUR / USD",
    isin: "LU0411078552",
    issuer: "DWS / Xtrackers",
    notes: "Daily 2x synthetic; compounding drag in sideways markets",
  },
  {
    leverage: "3x",
    ticker: "3USL / 3LUS",
    name: "WisdomTree S&P 500 3x Daily Leveraged",
    ter: "0.75% (OCF ~1.24%)",
    accDist: "Acc",
    currency: "USD / GBX",
    isin: "IE00B7Y34M31",
    issuer: "WisdomTree",
    notes: "Daily 3x ETP; sophisticated investors only",
  },
  {
    leverage: "3x",
    ticker: "3SPY",
    name: "Leverage Shares 3x Long US 500 ETP",
    ter: "0.75%",
    accDist: "Acc",
    currency: "USD",
    isin: "XS2472197149",
    issuer: "Leverage Shares",
    notes: "Physically backed 3x; trades like a stock on LSE",
  },
  {
    leverage: "1x",
    ticker: "SGLN",
    name: "iShares Physical Gold ETC",
    ter: "0.12%",
    accDist: "Acc",
    currency: "USD / GBP",
    isin: "IE00B4ND3602",
    issuer: "BlackRock iShares",
    notes: "Physical bullion; LSE GBP (SGLP) and USD lines; site back-test uses GC=F futures",
  },
  {
    leverage: "1x",
    ticker: "PHGP",
    name: "WisdomTree Physical Gold",
    ter: "0.39%",
    accDist: "Acc",
    currency: "USD",
    isin: "JE00B1VS3770",
    issuer: "WisdomTree",
    notes: "Physical gold ETC; Jersey listing",
  },
  {
    leverage: "1x",
    ticker: "GLD",
    name: "SPDR Gold Shares (US)",
    ter: "0.40%",
    accDist: "Acc",
    currency: "USD",
    isin: "US78463V1070",
    issuer: "State Street / SPDR",
    notes: "US-listed spot gold ETF; longest spot history from 2004",
  },
  {
    leverage: "1x",
    ticker: "IAU",
    name: "iShares Gold Trust (US)",
    ter: "0.25%",
    accDist: "Acc",
    currency: "USD",
    isin: "US4642851053",
    issuer: "BlackRock iShares",
    notes: "Lower-fee US spot gold ETF",
  },
  {
    leverage: "1x",
    ticker: "GC=F",
    name: "COMEX Gold Continuous (Yahoo)",
    ter: "—",
    accDist: "—",
    currency: "USD",
    isin: "—",
    issuer: "CME / data vendor",
    notes: "Futures roll series used for Guarded Gold tab signal/back-test; not directly investable",
  },
];
