#!/usr/bin/env python3
"""Regenerate the repo's DATA and EXPERIMENT catalogs.

    python tools/build_catalog.py

Scans the actual files on disk (so the catalog can never drift from reality) and
merges in curated source info from ``catalog/sources.json``. Writes:

    catalog/data.md,        catalog/data.json         - every dataset, its source + coverage
    catalog/experiments.md, catalog/experiments.json  - every backtest/analysis output dir

WHY THIS EXISTS (the whole point of the factory): so no agent re-downloads data or
re-runs a backtest that already exists.
  * Check ``catalog/data.md``        BEFORE downloading market data.
  * Check ``catalog/experiments.md`` BEFORE running a new backtest.

Stdlib only (no pandas) so it always runs. Idempotent and safe to run anytime.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "catalog"
OUTPUT = ROOT / "output"


def _csv_coverage(path: Path) -> dict:
    """Row count + first/last value of column 0 (the date) for a chronological CSV."""
    try:
        with path.open(newline="", encoding="utf-8", errors="replace") as fh:
            reader = csv.reader(fh)
            header = next(reader, None)
            first: str | None = None
            last: str | None = None
            n = 0
            for row in reader:
                if not row:
                    continue
                if first is None:
                    first = row[0]
                last = row[0]
                n += 1
        return {"rows": n, "start": first, "end": last, "columns": len(header or [])}
    except Exception as exc:  # never crash the catalog build
        return {"rows": 0, "start": None, "end": None, "columns": 0, "error": str(exc)}


def load_sources() -> dict:
    src = CATALOG / "sources.json"
    if src.exists():
        try:
            return json.loads(src.read_text(encoding="utf-8"))
        except Exception as exc:
            print(f"WARNING: could not parse catalog/sources.json ({exc}); using empty sources")
    return {"assets": [], "auxiliary": [], "etp_models": []}


def build_data_catalog(sources: dict) -> list[dict]:
    by_file = {a.get("file"): a for a in sources.get("assets", [])}
    rows: list[dict] = []
    for csv_path in sorted(ROOT.glob("*_daily.csv")):
        meta = by_file.get(csv_path.name, {})
        cov = _csv_coverage(csv_path)
        rows.append({
            "slug": meta.get("slug", csv_path.stem.replace("_daily", "")),
            "name": meta.get("name", "(UNCATALOGUED - add to catalog/sources.json)"),
            "ticker": meta.get("ticker", "?"),
            "source": meta.get("source", "?"),
            "file": csv_path.name,
            "rows": cov["rows"],
            "start": cov["start"],
            "end": cov["end"],
            "refresh": meta.get("refresh", "?"),
        })
    return rows


def build_experiment_catalog() -> list[dict]:
    rows: list[dict] = []
    if not OUTPUT.exists():
        return rows
    for d in sorted(p for p in OUTPUT.iterdir() if p.is_dir()):
        files = [f for f in d.rglob("*") if f.is_file()]
        key = sorted(f.name for f in files)[:6]
        rows.append({
            "experiment": d.name,
            "path": f"output/{d.name}/",
            "files": len(files),
            "key_files": key,
        })
    return rows


def write_data(rows: list[dict], sources: dict) -> None:
    (CATALOG / "data.json").write_text(
        json.dumps({"assets": rows,
                    "auxiliary": sources.get("auxiliary", []),
                    "etp_models": sources.get("etp_models", [])}, indent=2),
        encoding="utf-8")
    out = [
        "# Data catalog",
        "",
        "> GENERATED by `python tools/build_catalog.py` - do not hand-edit. Curated source facts live in `catalog/sources.json`.",
        "",
        "**Before downloading ANY market data, check this table.** If the asset is listed and the date range",
        "already covers what you need, DO NOT re-download - just load the CSV. To add a new source, follow",
        "`docs/runbooks/add-data-source.md`.",
        "",
        "| Slug | Asset | Ticker | File | Rows | Start | End | Refreshed by |",
        "|------|-------|--------|------|-----:|-------|-----|--------------|",
    ]
    for r in rows:
        out.append(f"| {r['slug']} | {r['name']} | `{r['ticker']}` | `{r['file']}` | "
                   f"{r['rows']} | {r['start']} | {r['end']} | {r['refresh']} |")
    aux = sources.get("auxiliary", [])
    if aux:
        out += ["", "## Auxiliary series (engine inputs, not tradable assets)", "",
                "| Name | Ticker | Use |", "|------|--------|-----|"]
        out += [f"| {a.get('name','')} | `{a.get('ticker','')}` | {a.get('use','')} |" for a in aux]
    etp = sources.get("etp_models", [])
    if etp:
        out += ["", "## Real ETP series (leverage modelling - `etp_leverage.py`)", "",
                "| Name | Ticker | Use |", "|------|--------|-----|"]
        out += [f"| {a.get('name','')} | `{a.get('ticker','')}` | {a.get('use','')} |" for a in etp]
    notes = sources.get("_data_notes", [])
    if notes:
        out += ["", "## Known data notes (read before downloading)", ""]
        out += [f"- {n}" for n in notes]
    out += ["", "_All sources: Yahoo Finance via `yfinance` (`data_manager.py`). Cleaning: `price_cleaning.py`._", ""]
    (CATALOG / "data.md").write_text("\n".join(out), encoding="utf-8")


def write_experiments(rows: list[dict]) -> None:
    (CATALOG / "experiments.json").write_text(
        json.dumps({"experiments": rows}, indent=2), encoding="utf-8")
    out = [
        "# Experiment catalog",
        "",
        "> GENERATED by `python tools/build_catalog.py` - do not hand-edit.",
        "",
        "Every backtest / analysis output directory under `output/`. **Before running a new backtest, scan",
        "this list** - if it already exists, build on it or re-check the result instead of duplicating work.",
        "",
        "**Canonical strategy sweep** (the master grid - start here):",
        "- `output/strategy_results/all_assets_combined.csv` + `output/strategy_results/<slug>_results.csv`",
        "- `Results/strategy_results.xlsx` - ~35 strategies x 10 assets, Water/Octane/Stillwater classified",
        "",
        "| Experiment | Path | Files | Sample outputs |",
        "|------------|------|------:|----------------|",
    ]
    for r in rows:
        kf = ", ".join(f"`{k}`" for k in r["key_files"]) if r["key_files"] else "-"
        out.append(f"| {r['experiment']} | `{r['path']}` | {r['files']} | {kf} |")
    out += ["", "_To register a new experiment: write outputs to `output/<your-id>/`, then re-run "
            "`python tools/build_catalog.py`. See `docs/runbooks/run-backtest.md`._", ""]
    (CATALOG / "experiments.md").write_text("\n".join(out), encoding="utf-8")


def main() -> None:
    CATALOG.mkdir(exist_ok=True)
    sources = load_sources()
    data_rows = build_data_catalog(sources)
    exp_rows = build_experiment_catalog()
    write_data(data_rows, sources)
    write_experiments(exp_rows)
    print(f"Data catalog:       {len(data_rows):>3} datasets    -> catalog/data.md")
    print(f"Experiment catalog: {len(exp_rows):>3} experiments -> catalog/experiments.md")


if __name__ == "__main__":
    main()
